// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class VoiceInfo {
    /**
     * Creates a new VoiceInfo instance.
     * @param {Partial<VoiceInfo>} [$$source = {}] - The source object to create the VoiceInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("lang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lang"] = "";
        }
        if (!("desc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoiceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VoiceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VoiceInfo(/** @type {Partial<VoiceInfo>} */($$parsedSource));
    }
}
