// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfigDir() {
    return $Call.ByID(4189990726);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenDevTools() {
    return $Call.ByID(192167535);
}

/**
 * @returns {$CancellablePromise<$models.AppConfig | null>}
 */
export function ReadConfig() {
    return $Call.ByID(3542173387).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.AppConfig | null} conf
 * @returns {$CancellablePromise<string>}
 */
export function WriteConfig(conf) {
    return $Call.ByID(128000622, conf);
}

// Private type creation functions
const $$createType0 = $models.AppConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
