// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as edge_tts$0 from "../../github.com/wujunwei928/edge-tts-go/edge_tts/models.js";

/**
 * @param {edge_tts$0.Voice} v
 * @param {string} r
 * @param {string} vo
 * @param {string} p
 * @param {string} outputPath
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function GenerateSpeech(v, r, vo, p, outputPath, content) {
    return $Call.ByID(1821302560, v, r, vo, p, outputPath, content);
}

/**
 * @returns {$CancellablePromise<edge_tts$0.Voice[]>}
 */
export function ListVoices() {
    return $Call.ByID(465703866).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = edge_tts$0.Voice.createFrom;
const $$createType1 = $Create.Array($$createType0);
