// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ConfigService from "./configservice.js";
import * as EdgeTtsService from "./edgettsservice.js";
import * as NativeTts from "./nativetts.js";
import * as OsService from "./osservice.js";
export {
    ConfigService,
    EdgeTtsService,
    NativeTts,
    OsService
};

export {
    AppConfig
} from "./models.js";
