// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as GreetService from "./greetservice.js";
import * as NativeTts from "./nativetts.js";
export {
    GreetService,
    NativeTts
};
