// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetOs() {
    return $Call.ByID(3792000209);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFile(path) {
    return $Call.ByID(1223424991, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolder(path) {
    return $Call.ByID(3657682329, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function PathStat(path) {
    return $Call.ByID(1196189020, path);
}
