// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetOs(): $CancellablePromise<string> {
    return $Call.ByID(3792000209);
}

export function OpenFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1223424991, path);
}

export function OpenFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(3657682329, path);
}
