// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Voice {
    /**
     * Creates a new Voice instance.
     * @param {Partial<Voice>} [$$source = {}] - The source object to create the Voice.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("ShortName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ShortName"] = "";
        }
        if (!("Gender" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Gender"] = "";
        }
        if (!("Locale" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Locale"] = "";
        }
        if (!("SuggestedCodec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SuggestedCodec"] = "";
        }
        if (!("FriendlyName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FriendlyName"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("VoiceTag" in $$source)) {
            /**
             * @member
             * @type {VoiceTag}
             */
            this["VoiceTag"] = (new VoiceTag());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Voice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Voice}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("VoiceTag" in $$parsedSource) {
            $$parsedSource["VoiceTag"] = $$createField7_0($$parsedSource["VoiceTag"]);
        }
        return new Voice(/** @type {Partial<Voice>} */($$parsedSource));
    }
}

export class VoiceTag {
    /**
     * Creates a new VoiceTag instance.
     * @param {Partial<VoiceTag>} [$$source = {}] - The source object to create the VoiceTag.
     */
    constructor($$source = {}) {
        if (!("ContentCategories" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ContentCategories"] = [];
        }
        if (!("VoicePersonalities" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["VoicePersonalities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoiceTag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VoiceTag}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ContentCategories" in $$parsedSource) {
            $$parsedSource["ContentCategories"] = $$createField0_0($$parsedSource["ContentCategories"]);
        }
        if ("VoicePersonalities" in $$parsedSource) {
            $$parsedSource["VoicePersonalities"] = $$createField1_0($$parsedSource["VoicePersonalities"]);
        }
        return new VoiceTag(/** @type {Partial<VoiceTag>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = VoiceTag.createFrom;
const $$createType1 = $Create.Array($Create.Any);
